/* DO NOT EDIT THIS FILE - it is machine generated */
#include <stdio.h>
#include <string.h>
#include <memory>
#ifndef _WIN32
    #include <libgen.h>
    #include <dirent.h>
#endif
#include <stdlib.h>
#include <stdexcept>

#include "AudioStreamInput.h"
#include "Metadata.h"
#include "Codegen.h"
#include <jni.h>
#include <string>

/* Header for class HelloWorld */
 
#ifndef _Included_Echoprint
#define _Included_Echoprint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Echoprint
 * Method:    code
 * Signature: ()V
 */
JNIEXPORT jstring JNICALL Java_com_playax_fingerprint_Echoprint_code(JNIEnv *, jobject, jstring);
 
#ifdef __cplusplus
}
#endif
#endif
